[workspace]
resolver = "2"
members = ["runner"]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1.0.80"
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["full"] }
